### PR TITLE
Reexport quickcheck

### PR DESCRIPTION
**Pull request by annenkov**
## Purpose

Make `quickcheck` available when writing property based tests. This is useful for defining `Arbitrary` instances for custom data types in smart contracts.

### CODE REVIEW

**Review by Bargsteen — APPROVED** [review]
LGTM. But it should also go into the changelog.

**Comment by abizjak** [comment]
I am not convinced this is a good idea. We are not re-exporting third-party libraries in this crate and I am not sure we should.

What is the problem of just adding that dependency wherever it is needed?

**Comment by annenkov** [comment]
After some discussions it was decided not to re-export `quickcheck`, but use it in a smart contract as a dependency. That is, by adding in the smart contract's project `Cargo.toml`

```toml
[dependencies]
quickcheck = { version = "1.0.3"}
```

**Comment by abizjak** [comment]
> What are the downsides of re-exporting?

To document here, the downside is that it makes the public API larger and maintenance more complex. It's a tradeoff and at this time it seems it is better to not re-export.

**Pull request closed without merging**
